In [13]:
%pip install galois
import galois
import numpy as np

p=71

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [4]:
print (-5 % p)
print(pow(5, -1, p))

66
57


In [5]:
## Problem 1

#Find the elements in a finite field that are congruent to the following values:

#  -1
#  -4
#  -160
#  500

print(-1 % p)
print(-4 % p)
print(-160 % p)
print(500 % p)

70
67
53
3


In [13]:
## Problem 2

# Find the elements that are congruent to a = 5/6, b = 11/12, and c = 21/12

# Verify your answer by checking that a + b = c (in the finite field)

a = 5 * pow(6, -1, p) % p
b = 11 * pow(12, -1, p) % p
c = 21 * pow(12, -1, p) % p
print(a, b, c)

print((a + b) % p)
print((a + b) % p == c)



60 66 55
55
True


In [14]:
## Problem 3

# Find the elements that are congruent to a = 2/3, b = 1/2, and c = 1/3.

# Verify your answer by checking that a * b = c (in the finite field)

a = 2 * pow(3, -1, p) % p
b = 1 * pow(2, -1, p) % p
c = 1 * pow(3, -1, p) % p
print(a, b, c)

print((a * b) % p)
print((a * b) % p == c)

48 36 24
24
True


## Problem 4

The inverse of a 2 x 2 matrix $A$ is

$$
A^{-1}=\frac{1}{\text{det}}\begin{bmatrix}d & -b\\-c & a\end{bmatrix}
$$

where $A$ is

$$
A = \begin{bmatrix}a & b\\c & d\end{bmatrix}
$$
 
And the determinant det is

$$
\text{det}=a \times d-b\times c
$$

Compute the inverse of the following matrix in the finite field:

$$
\begin{bmatrix}1 & 1\\1 & 4\end{bmatrix}
$$

Verify your answer by checking that

$$
AA^{-1}=I
$$

Where $I$ is the identity matrix.

In [38]:

a = 1
b = 1
c = 1
d = 4
A = np.array([[a, b], [c, d]])
print(A)

det = a * d - b * c
print(det)

a_inv = d
b_inv = -b % p
c_inv = -c % p
d_inv = a
print(a_inv, b_inv, c_inv, d_inv)
det_inv = pow(det, -1, p)
print('det_inv:', det_inv)
A_inv = det_inv * np.array([[a_inv, b_inv], [c_inv, d_inv]])
print(A_inv)
A_inv_mod = A_inv % p
print('A_inv_mod:\n', A_inv_mod)

print('A @ A_inv_mod:\n', (A @ A_inv_mod) % p)


[[1 1]
 [1 4]]
3
4 70 70 1
det_inv: 24
[[  96 1680]
 [1680   24]]
A_inv_mod:
 [[25 47]
 [47 24]]
A @ A_inv_mod:
 [[1 0]
 [0 1]]


In [41]:
## Problem 5

# What is the modular square root of 12?

# Verify your answer by checking that x * x = 12 (mod 71)

# Use brute force to find the answer (in Python)

for x in range(p):
    if (x * x) % p == 12:
        r = x
        break
print(r)
print((r * r) % p)


15
12


## Problem 6

Suppose we have the following polynomials:

$$
p(x)=52x^2+24x+61\\q(x)=40x^2+40x+58
$$

What is p(x) + q(x)? What is p(x) * q(x)?

Use the `galois` library in Python to find the roots of p(x) and q(x).

What are the roots of p(x)q(x)?

In [28]:
GF = galois.GF(p)
# pp = GF([52, 24, 61])
pp = galois.Poly([52, 24, 61], field=GF)
qq = galois.Poly([40, 40, 58], field=GF)
print(pp + qq)

# 2080 x^4 + 3040 x^3 + 6416 x^2 + 3832 x + 3538
vec = np.array([2080, 3040, 6416, 3832, 3538])
vec_mod = vec % p
print(vec_mod)

ppqq = pp * qq
print('ppqq:', ppqq)

ppr = pp.roots()
qqr = qq.roots()
print('pp.roots():', ppr)
print('qq.roots():', qqr)

print('ppqq.roots():', ppr, qqr)





21x^2 + 64x + 48
[21 58 26 69 59]
ppqq: 21x^4 + 58x^3 + 26x^2 + 69x + 59
pp.roots(): [34 42]
qq.roots(): []
ppqq.roots(): [34 42] []


In [33]:
## Problem 7

# Find a polynomial f(x) that crosses the points (10, 15), (23, 29).

# Since these are two points, the polynomial will be of degree 1 and be the equation for a line (y = ax + b).

# Verify your answer by checking that f(10) = 15 and f(23) = 29.

a = (29 - 15) *  pow(23 - 10, -1, p) % p
b = (15 - a * 10) % p
print(a, b)

print('(a * 10 + b) % p:', (a * 10 + b) % p)
print('(a * 23 + b) % p:', (a * 23 + b) % p)


12 37
(a * 10 + b) % p: 15
(a * 23 + b) % p: 29


In [35]:
## Problem 8

# What is Lagrange interpolation and what does it do?

# Find a polynomial that crosses through the points (0, 1), (1, 2), (2, 1).

# Use this Stackoverflow answer as a starting point: https://stackoverflow.com/a/73434775

GF = galois.GF(p)

x = GF([0, 1, 2])
y = GF([1, 2, 1])

f = galois.lagrange_poly(x, y)
print(f)

print(f(0), f(1), f(2))




70x^2 + 2x + 1
1 2 1
